Remove redefinition of nullptr that caused compilation errors under Qt 5.14.
Thanks to mjphyi for tracking this down!

gcc didn't provide very useful error messages, saying that
error: invalid conversion from ‘long int’ to ‘QDebug::Stream*’
was in qglobal.h.

But it really had to do with a few scattered #defines in OSCAR changing
nullptr to NULL (an int). Since OSCAR now requires C++11, and nullptr
is a keyword in C++11, these #defines can go.

Resolves issue #5.